#第一个member表示模块，第二个member表示表
#在header(请求头)加参数，不需要空一行，例如token参数，但是如果body里面加参数，就需要空一行，例如下面两个请求
GET http://localhost:8000/member/member/count
Accept: application/json
token: 123

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile = 139

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "13965962003"
}

###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13000000001",
  "code": "8888"
}


> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("test_token", response.body.content.token);
%}


###