#第一个member表示模块，第二个member表示表
GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile =139

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/x-www-form-urlencoded

mobile =13965962003

###